apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
  - protocol: TCP
    port: 8081       # The port exposed by the service
    targetPort: 9092 # The port on the container to forward to
    nodePort: 30007  # The specific NodePort to expose on the node
