apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-0
  template:
    metadata:
      labels:
        app: test-app-0
    spec:
      containers:
        - name: test-app-0
          image: wishula/test-app:latest
          resources:
            requests:
              cpu: "0.5"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          ports:
            - containerPort: 8085
          readinessProbe:
            httpGet:
              path: /
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-service-0
spec:
  selector:
    app: test-app-0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: ClusterIP
