apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: latency-test-rules
  namespace: monitoring
spec:
  groups:
    - name: latency-spike-rules
      rules:
        - alert: PodLatencySpike
          expr: rate(http_request_duration_seconds_sum{namespace="latency-test"}[1m]) > 1
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Latency Spike Detected"
            description: "Pod {{ $labels.pod }} in {{ $labels.namespace }} is experiencing latency spikes."
