apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: wishula/order-service:1.0
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "128Mi"  # Minimum memory required for the container
            cpu: "250m"      # Minimum CPU required for the container
          limits:
            memory: "256Mi"  # Maximum memory the container can use
            cpu: "500m"      # Maximum CPU the container can use
