apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: wishula/order-service:1.0
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"  # Minimum memory required for the container
            cpu: "256m"      # Minimum CPU required for the container
          limits:
            memory: "512Mi"  # Maximum memory the container can use
            cpu: "512m"      # Maximum CPU the container can use
