#Author: Wishula Jayathunga
apiVersion: v1
kind: Service
metadata:
  name: order-service-2
spec:
  selector:
    app: order-service-2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-2
  template:
    metadata:
      labels:
        app: order-service-2
    spec:
      containers:
        - name: order-service-2
          image: wishula/order-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "order-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "1234"
            - name: DB_NAME
              value: "orderdb"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:8081"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service:8082"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "orderdb"
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
spec:
  selector:
    app: order-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30001
  type: NodePort
