apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: flask-app
          image: wishula/flask-prometheus-app:latest
          ports:
            - containerPort: 5000 
          resources:
            requests:
              memory: "100Mi"
              cpu: "500m"
            limits:
              memory: "200Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: default
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
