apiVersion: v1
kind: Service
metadata:
  name: payment-service-2
spec:
  selector:
    app: payment-service-2
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30004
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service-2
  template:
    metadata:
      labels:
        app: payment-service-2
    spec:
      containers:
        - name: payment-service-2
          image: wishula/payment-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              value: "payment-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "1234"
            - name: DB_NAME
              value: "paymentdb"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "paymentdb"
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
spec:
  selector:
    app: payment-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30005
  type: NodePort
