apiVersion: v1
kind: Service
metadata:
  name: product-service-2
spec:
  selector:
    app: product-service-2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service-2
  template:
    metadata:
      labels:
        app: product-service-2
    spec:
      containers:
        - name: product-service-2
          image: wishula/product-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: "product-db"  # Change to the product-db service name
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "1234"
            - name: DB_NAME
              value: "productdb"
          resources:
            requests:
              memory: "256Mi"
              cpu: "253m"
            limits:
              memory: "350Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "productdb"
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-db
spec:
  selector:
    app: product-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30003
  type: NodePort
