apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 8080       # The port exposed by the service
    targetPort: 9090 # The port on the container to forward to
    nodePort: 30006  # The specific NodePort to expose on the node
