apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: wishula/my-flask-app:latest
          resources:
            requests:
              cpu: "250m"  # 250 millicores (0.25 vCPU)
            limits:
              cpu: "500m"   # 500 millicores (0.5 vCPU)
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 82      # Expose service on port 80
      targetPort: 5000  # Forward to Flask app's container port
  type: NodePort  # Change to NodePort or LoadBalancer if needed
