apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - name: app-container
        image: "nginx:latest"
        ports:
        - containerPort: 80  # Nginx's default port
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 0.5
            memory: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-deployment
  ports:
    - protocol: TCP
      port: 80   # External port
      targetPort: 80   # Nginx's default port
      nodePort: 30081  # Port exposed on each node
  type: NodePort  # This exposes the service externally on a node port
