apiVersion: v1
kind: Service
metadata:
  name: order-service-1
spec:
  type: NodePort
  selector:
    app: order-service-1
  ports:
  - protocol: TCP
    port: 8080       # The port exposed by the service
    targetPort: 9091 # The port on the container to forward to
    nodePort: 30008  # The specific NodePort to expose on the node
