apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: test-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: python:3.9
          command: ["python", "-m", "http.server", "8084"]
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
            limits:
              cpu: "1.0"
              memory: "1Gi"
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: test-namespace
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: ClusterIP
